export const Data = [
    {
        "id": 0,
        "price": "550000",
        "date": "2024-07-01",
        "status": "판매중",
        "author": "토끼풀",
        "image": ["/images/postImg1.jpeg"],
        "description": "성능 뛰어나고 상태 매우 좋은 중고 노트북입니다.",
        "title": "갤럭시북3 판매해요!!",
        "category": "디지털",
        "condition": "중고상품",
        "delivery": "무료배송",
        "coordinate": { "lat": 37.556612, "lon": 126.922667 }
    },
    {
        "id": 1,
        "price": "450000",
        "date": "2024-07-02",
        "status": "판매중",
        "author": "미소라떼",
        "image": ["/images/postImg2.jpeg"],
        "description": "최상의 상태를 유지하고 있는 고급 중고 자전거입니다.",
        "title": "고급 자전거 판매합니다.",
        "category": "스포츠 / 레저",
        "condition": "중고상품",
        "delivery": "무료배송",
        "coordinate": { "lat": 37.464507, "lon": 126.961904 }
    },
    {
        "id": 2,
        "price": "1050000",
        "date": "2024-07-03",
        "status": "예약중",
        "author": "푸딩쿠키",
        "image": ["/images/postImg3.jpeg"],
        "description": "사용감 거의 없는 최신 중고 아이폰 모델입니다.",
        "title": "아이폰15 256gb",
        "category": "디지털",
        "condition": "중고상품",
        "delivery": "무료배송",
        "coordinate": { "lat": 37.519548, "lon": 127.075421 }
    },
    {
        "id": 3,
        "price": "70000",
        "date": "2024-07-04",
        "status": "판매완료",
        "author": "꿈나무파이",
        "image": ["/images/postImg4.jpeg"],
        "description": "사용감 적은 중고 책상입니다.",
        "title": "중소형 책상 판매해요",
        "category": "가구 / 인테리어",
        "condition": "중고상품",
        "delivery": "무료배송",
        "coordinate": { "lat": 37.642498, "lon": 127.116901 }
    },
    {
        "id": 4,
        "price": "850000",
        "date": "2024-07-05",
        "status": "판매중",
        "author": "귀염뽀송",
        "image": ["/images/postImg5.jpg"],
        "description": "튼튼하고 내구성 좋은 중고 캠핑 텐트입니다.",
        "title": "고급 캠핑 텐트 판매합니다.",
        "category": "스포츠 / 레저",
        "condition": "중고상품",
        "delivery": "무료배송",
        "coordinate": { "lat": 37.495753, "lon": 126.885496 }
    },
    {
        "id": 5,
        "price": "480000",
        "date": "2024-07-06",
        "status": "판매중",
        "author": "토끼콩",
        "image": ["/images/postImg6.jpeg"],
        "description": "우수한 성능을 자랑하는 최신 중고 드론입니다.",
        "title": "최신 드론 판매합니다.",
        "category": "기타",
        "condition": "중고상품",
        "delivery": "무료배송",
        "coordinate": { "lat": 37.521537, "lon": 127.027607 }
    },
    {
        "id": 6,
        "price": "320000",
        "date": "2024-07-07",
        "status": "예약중",
        "author": "짹짹이",
        "image": ["/images/postImg7.jpeg"],
        "description": "사용감 적고 성능 좋은 중고 스마트워치입니다.",
        "title": "애플워치6",
        "category": "전자기기",
        "condition": "중고상품",
        "delivery": "무료배송",
        "coordinate": { "lat": 37.567895, "lon": 126.995238 }
    },
    {
        "id": 7,
        "price": "120000",
        "date": "2024-07-08",
        "status": "판매중",
        "author": "황금망고",
        "image": ["/images/postImg8.jpeg"],
        "description": "음색 아주 좋은 입문용 중고 기타입니다.",
        "title": "고퍼우드 g110",
        "category": "음반 / 악기",
        "condition": "중고상품",
        "delivery": "무료배송",
        "coordinate": { "lat": 37.459342, "lon": 127.011246 }
    },
    {
        "id": 8,
        "price": "850000",
        "date": "2024-07-09",
        "status": "판매완료",
        "author": "웃음꽃",
        "image": ["/images/postImg9.jpeg"],
        "description": "화질 우수하고 최신 기술 탑재된 중고 풀HD TV입니다.",
        "title": "lg 풀HD TV 판매해요",
        "category": "가전 제품",
        "condition": "중고상품",
        "delivery": "무료배송",
        "coordinate": { "lat": 37.613264, "lon": 126.955214 }
    },
    {
        "id": 9,
        "price": "450000",
        "date": "2024-07-10",
        "status": "판매중",
        "author": "꼬부기",
        "image": ["/images/postImg10.jpeg"],
        "description": "음질 최상의 성능을 자랑하는 고급 중고 스피커입니다.",
        "title": "마샬 스탠모어 판매합니다.",
        "category": "음반 / 악기",
        "condition": "중고상품",
        "delivery": "무료배송",
        "coordinate": { "lat": 37.536512, "lon": 127.089476 }
    },
    {
        "id": 10,
        "price": "55000",
        "date": "2024-07-11",
        "status": "판매중",
        "author": "반짝이별",
        "image": ["/images/postImg11.jpeg"],
        "description": "다양한 색상으로 조절 가능한 중고 인테리어 조명입니다.",
        "title": "다기능 인테리어 조명 판매",
        "category": "가구 / 인테리어",
        "condition": "중고상품",
        "delivery": "무료배송",
        "coordinate": { "lat": 37.589437, "lon": 127.035108 }
    },
    {
        "id": 11,
        "price": "25000",
        "date": "2024-07-12",
        "status": "판매중",
        "author": "허니버니",
        "image": ["/images/postImg12.jpeg"],
        "description": "다양한 사이즈가 있는 새 옷입니다.",
        "title": "스투시 반팔 판매",
        "category": "남성 의류",
        "condition": "새상품",
        "delivery": "무료배송",
        "coordinate": { "lat": 37.458619, "lon": 126.977361 }
    },
    {
        "id": 12,
        "price": "35000",
        "date": "2024-07-13",
        "status": "예약중",
        "author": "흥하자",
        "image": ["/images/postImg13.jpeg"],
        "description": "다양한 장르를 포함한 중고 책입니다.",
        "title": "자바스크립트 딥다이브 판매",
        "category": "도서 / 티켓 / 문구",
        "condition": "중고상품",
        "delivery": "무료배송",
        "coordinate": { "lat": 37.673015, "lon": 127.061583 }
    },
    {
        "id": 13,
        "price": "55000",
        "date": "2024-07-14",
        "status": "판매완료",
        "author": "깜짝곰",
        "image": ["/images/postImg14.jpeg"],
        "description": "경량화된 디자인의 중고 자전거입니다.",
        "title": "중고 삼천리 자전거 판매",
        "category": "스포츠 / 레저",
        "condition": "중고상품",
        "delivery": "무료배송",
        "coordinate": { "lat": 37.527184, "lon": 127.038216 }
    },
    {
        "id": 14,
        "price": "45000",
        "date": "2024-07-15",
        "status": "판매중",
        "author": "뚜루뚜",
        "image": ["/images/postImg15.jpeg"],
        "description": "최고의 음질을 제공하는 중고 헤드셋입니다.",
        "title": "qcy 헤드셋 판매",
        "category": "기타",
        "condition": "중고상품",
        "delivery": "무료배송",
        "coordinate": { "lat": 37.511738, "lon": 126.898146 }
    },
    {
        "id": 15,
        "price": "25000",
        "date": "2024-07-16",
        "status": "판매중",
        "author": "철쭉",
        "image": ["/images/postImg16.jpeg"],
        "description": "다양한 과목을 포함한 리액트 학습용 중고 책입니다.",
        "title": "러닝 리액트 판매합니다.",
        "category": "도서 / 티켓 / 문구",
        "condition": "중고상품",
        "delivery": "무료배송",
        "coordinate": { "lat": 37.487052, "lon": 127.023974 }
    },
    {
        "id": 16,
        "price": "32000",
        "date": "2024-07-17",
        "status": "판매중",
        "author": "포푸라브",
        "image": ["/images/postImg17.jpeg"],
        "description": "다양한 종류를 포함한 로컬국밥 도시락입니다.",
        "title": "로컬국밥 도시락 판매",
        "category": "식품",
        "condition": "새상품",
        "delivery": "무료배송",
        "coordinate": { "lat": 37.669724, "lon": 127.121983 }
    },
    {
        "id": 17,
        "price": "290000",
        "date": "2024-07-18",
        "status": "판매중",
        "author": "초코님",
        "image": ["/images/postImg18.jpeg"],
        "description": "커피 맛이 아주 좋은 중고 커피 머신입니다.",
        "title": "네스프레소 머신 판매",
        "category": "가전 제품",
        "condition": "중고상품",
        "delivery": "무료배송",
        "coordinate": { "lat": 37.474394, "lon": 126.968495 }
    },
    {
        "id": 18,
        "price": "420000",
        "date": "2024-07-19",
        "status": "판매중",
        "author": "달달곰",
        "image": ["/images/postImg19.jpeg"],
        "description": "해상도가 아주 좋은 새 풀HD 모니터입니다.",
        "title": "풀HD 모니터 판매합니다",
        "category": "가전 제품",
        "condition": "새상품",
        "delivery": "무료배송",
        "coordinate": { "lat": 37.658923, "lon": 126.957483 }
    },
    {
        "id": 19,
        "price": "310000",
        "date": "2024-07-19",
        "status": "판매중",
        "author": "행복꽃",
        "image": ["/images/postImg20.jpeg"],
        "description": "밝기 조절이 가능한 감성 조명입니다.",
        "title": "감성 조명 판매",
        "category": "가구 / 인테리어",
        "condition": "새상품",
        "delivery": "무료배송",
        "coordinate": { "lat": 37.516138, "lon": 126.942083 }
    }
];
